[tool.poetry]
name = "cagrex"
version = "0.2.1"
description = "Extractor for UFSC's undergrad courses management system."
authors = ["Caravela Hacker Club"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
mechanicalsoup = "^0.11.0"
bs4 = "^0.0.1"
pprint = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
